// 1. WITHDRAWAL
export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";

// 2. WITHDRAWAL_PROCEED
export const WITHDRAWAL_PROCEED_REQUEST = "WITHDRAWAL_PROCEED_REQUEST";
export const WITHDRAWAL_PROCEED_SUCCESS = "WITHDRAWAL_PROCEED_SUCCESS";
export const WITHDRAWAL_PROCEED_FAILURE = "WITHDRAWAL_PROCEED_FAILURE";

// 3. GET_WITHDRAWAL_HISTORY
export const GET_WITHDRAWAL_HISTORY_REQUEST = "GET_WITHDRAWAL_HISTORY_REQUEST";
export const GET_WITHDRAWAL_HISTORY_SUCCESS = "GET_WITHDRAWAL_HISTORY_SUCCESS";
export const GET_WITHDRAWAL_HISTORY_FAILURE = "GET_WITHDRAWAL_HISTORY_FAILURE";

// / 3. GET_WITHDRAWAL_REQUEST_REQUEST
export const GET_WITHDRAWAL_REQUEST_REQUEST = "GET_WITHDRAWAL_REQUEST_REQUEST";
export const GET_WITHDRAWAL_SUCCESS_SUCCESS = "GET_WITHDRAWAL_SUCCESS_SUCCESS";
export const GET_WITHDRAWAL_FAILURE_FAILURE = "GET_WITHDRAWAL_FAILURE_FAILURE";

// 4. ADD_PAYMENT_DETAILS
export const ADD_PAYMENT_DETAILS_REQUEST = "ADD_PAYMENT_DETAILS_REQUEST";
export const ADD_PAYMENT_DETAILS_SUCCESS = "ADD_PAYMENT_DETAILS_SUCCESS";
export const ADD_PAYMENT_DETAILS_FAILURE = "ADD_PAYMENT_DETAILS_FAILURE";

// 5. GET_PAYMENT_DETAILS
export const GET_PAYMENT_DETAILS_REQUEST = "GET_PAYMENT_DETAILS_REQUEST";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";
export const GET_PAYMENT_DETAILS_FAILURE = "GET_PAYMENT_DETAILS_FAILURE";
